name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: Run Unit tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup Playwright
        run: npx playwright install-deps

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:units

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage/
